export const brands = [
  {
    id: 'apple',
    name: 'Apple',
    description: 'Premium technology and electronics',
    logo: '/brands/apple.png',
    slug: 'apple',
    categoryIds: ['electronics', 'smartphones', 'laptops'],
    country: 'US',
    foundedYear: 1976,
    website: 'https://apple.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 1,
  },
  {
    id: 'samsung',
    name: 'Samsung',
    description: 'Global electronics and appliances',
    logo: '/brands/samsung.png',
    slug: 'samsung',
    categoryIds: ['electronics', 'smartphones', 'laptops', 'home_garden'],
    country: 'KR',
    foundedYear: 1938,
    website: 'https://samsung.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 2,
  },
  {
    id: 'nike',
    name: 'Nike',
    description: 'Athletic footwear and apparel',
    logo: '/brands/nike.png',
    slug: 'nike',
    categoryIds: ['fashion', 'sports_outdoors', 'mens_fashion', 'womens_fashion'],
    country: 'US',
    foundedYear: 1964,
    website: 'https://nike.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 3,
  },
  {
    id: 'adidas',
    name: 'Adidas',
    description: 'Sports clothing and accessories',
    logo: '/brands/adidas.png',
    slug: 'adidas',
    categoryIds: ['fashion', 'sports_outdoors'],
    country: 'DE',
    foundedYear: 1949,
    website: 'https://adidas.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 4,
  },
  {
    id: 'sony',
    name: 'Sony',
    description: 'Consumer electronics and entertainment',
    logo: '/brands/sony.png',
    slug: 'sony',
    categoryIds: ['electronics', 'books_media'],
    country: 'JP',
    foundedYear: 1946,
    website: 'https://sony.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 5,
  },
  {
    id: 'huawei',
    name: 'Huawei',
    description: 'Telecommunications and consumer electronics',
    logo: '/brands/huawei.png',
    slug: 'huawei',
    categoryIds: ['electronics', 'smartphones'],
    country: 'CN',
    foundedYear: 1987,
    website: 'https://huawei.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 6,
  },
  {
    id: 'xiaomi',
    name: 'Xiaomi',
    description: 'Smartphones and smart devices',
    logo: '/brands/xiaomi.png',
    slug: 'xiaomi',
    categoryIds: ['electronics', 'smartphones'],
    country: 'CN',
    foundedYear: 2010,
    website: 'https://mi.com',
    isPremium: false,
    isVerified: true,
    sortOrder: 7,
  },
  {
    id: 'tecno',
    name: 'Tecno',
    description: 'Affordable smartphones and electronics',
    logo: '/brands/tecno.png',
    slug: 'tecno',
    categoryIds: ['electronics', 'smartphones'],
    country: 'CN',
    foundedYear: 2006,
    website: 'https://tecno-mobile.com',
    isPremium: false,
    isVerified: true,
    sortOrder: 8,
  },
  {
    id: 'infinix',
    name: 'Infinix',
    description: 'Budget-friendly smartphones',
    logo: '/brands/infinix.png',
    slug: 'infinix',
    categoryIds: ['electronics', 'smartphones'],
    country: 'CN',
    foundedYear: 2013,
    website: 'https://infinixmobility.com',
    isPremium: false,
    isVerified: true,
    sortOrder: 9,
  },
  {
    id: 'safaricom',
    name: 'Safaricom',
    description: 'Telecommunications and mobile services',
    logo: '/brands/safaricom.png',
    slug: 'safaricom',
    categoryIds: ['electronics'],
    country: 'KE',
    foundedYear: 1997,
    website: 'https://safaricom.co.ke',
    isPremium: true,
    isVerified: true,
    sortOrder: 10,
  },
  {
    id: 'brookside',
    name: 'Brookside',
    description: 'Dairy products and beverages',
    logo: '/brands/brookside.png',
    slug: 'brookside',
    categoryIds: ['home_garden'],
    country: 'KE',
    foundedYear: 1993,
    website: 'https://brookside.co.ke',
    isPremium: false,
    isVerified: true,
    sortOrder: 11,
  },
  {
    id: 'kim-fay',
    name: 'Kim-Fay',
    description: 'Automotive parts and accessories',
    logo: '/brands/kim-fay.png',
    slug: 'kim-fay',
    categoryIds: ['automotive'],
    country: 'KE',
    foundedYear: 1970,
    website: 'https://kimfay.com',
    isPremium: false,
    isVerified: true,
    sortOrder: 12,
  },
  {
    id: 'bidco',
    name: 'Bidco',
    description: 'Consumer goods and household products',
    logo: '/brands/bidco.png',
    slug: 'bidco',
    categoryIds: ['home_garden'],
    country: 'KE',
    foundedYear: 1985,
    website: 'https://bidcoafrica.com',
    isPremium: false,
    isVerified: true,
    sortOrder: 13,
  },
  {
    id: 'dell',
    name: 'Dell',
    description: 'Computers and technology solutions',
    logo: '/brands/dell.png',
    slug: 'dell',
    categoryIds: ['electronics', 'laptops'],
    country: 'US',
    foundedYear: 1984,
    website: 'https://dell.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 14,
  },
  {
    id: 'hp',
    name: 'HP',
    description: 'Computers and printing solutions',
    logo: '/brands/hp.png',
    slug: 'hp',
    categoryIds: ['electronics', 'laptops'],
    country: 'US',
    foundedYear: 1939,
    website: 'https://hp.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 15,
  },
  {
    id: 'lenovo',
    name: 'Lenovo',
    description: 'Computers and mobile devices',
    logo: '/brands/lenovo.png',
    slug: 'lenovo',
    categoryIds: ['electronics', 'laptops'],
    country: 'CN',
    foundedYear: 1984,
    website: 'https://lenovo.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 16,
  },
  {
    id: 'lg',
    name: 'LG',
    description: 'Electronics and home appliances',
    logo: '/brands/lg.png',
    slug: 'lg',
    categoryIds: ['electronics', 'home_garden'],
    country: 'KR',
    foundedYear: 1947,
    website: 'https://lg.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 17,
  },
  {
    id: 'bosch',
    name: 'Bosch',
    description: 'Home appliances and power tools',
    logo: '/brands/bosch.png',
    slug: 'bosch',
    categoryIds: ['home_garden', 'automotive'],
    country: 'DE',
    foundedYear: 1886,
    website: 'https://bosch.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 18,
  },
  {
    id: 'philips',
    name: 'Philips',
    description: 'Healthcare and consumer electronics',
    logo: '/brands/philips.png',
    slug: 'philips',
    categoryIds: ['electronics', 'home_garden'],
    country: 'NL',
    foundedYear: 1891,
    website: 'https://philips.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 19,
  },
  {
    id: 'unilever',
    name: 'Unilever',
    description: 'Consumer goods and personal care',
    logo: '/brands/unilever.png',
    slug: 'unilever',
    categoryIds: ['beauty_health', 'home_garden'],
    country: 'GB',
    foundedYear: 1929,
    website: 'https://unilever.com',
    isPremium: false,
    isVerified: true,
    sortOrder: 20,
  },
  {
    id: 'puma',
    name: 'Puma',
    description: 'Sports and lifestyle brand',
    logo: '/brands/puma.png',
    slug: 'puma',
    categoryIds: ['fashion', 'sports_outdoors'],
    country: 'DE',
    foundedYear: 1948,
    website: 'https://puma.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 21,
  },
  {
    id: 'canon',
    name: 'Canon',
    description: 'Cameras and imaging products',
    logo: '/brands/canon.png',
    slug: 'canon',
    categoryIds: ['electronics'],
    country: 'JP',
    foundedYear: 1937,
    website: 'https://canon.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 22,
  },
  {
    id: 'nintendo',
    name: 'Nintendo',
    description: 'Video games and consoles',
    logo: '/brands/nintendo.png',
    slug: 'nintendo',
    categoryIds: ['toys_games'],
    country: 'JP',
    foundedYear: 1889,
    website: 'https://nintendo.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 23,
  },
  {
    id: 'lego',
    name: 'LEGO',
    description: 'Construction toys and games',
    logo: '/brands/lego.png',
    slug: 'lego',
    categoryIds: ['toys_games'],
    country: 'DK',
    foundedYear: 1932,
    website: 'https://lego.com',
    isPremium: true,
    isVerified: true,
    sortOrder: 24,
  },
  {
    id: 'colgate',
    name: 'Colgate',
    description: 'Oral care and personal hygiene',
    logo: '/brands/colgate.png',
    slug: 'colgate',
    categoryIds: ['beauty_health'],
    country: 'US',
    foundedYear: 1806,
    website: 'https://colgate.com',
    isPremium: false,
    isVerified: true,
    sortOrder: 25,
  },
  {
    id: 'nestle',
    name: 'Nestlé',
    description: 'Food and beverage products',
    logo: '/brands/nestle.png',
    slug: 'nestle',
    categoryIds: ['home_garden'],
    country: 'CH',
    foundedYear: 1866,
    website: 'https://nestle.com',
    isPremium: false,
    isVerified: true,
    sortOrder: 26,
  },
] as const;

export type BrandId = typeof brands[number]['id'];

export const brandMap = brands.reduce((acc, brand) => {
  acc[brand.id] = brand;
  return acc;
}, {} as Record<BrandId, typeof brands[number]>);

export const slugToBrandMap = brands.reduce((acc, brand) => {
  acc[brand.slug] = brand;
  return acc;
}, {} as Record<string, typeof brands[number]>);

export function getBrandsByCategory(categoryId: string): typeof brands {
  return brands.filter(brand => 
    brand.categoryIds.includes(categoryId as any)
  ).sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getPremiumBrands(): typeof brands {
  return brands.filter(brand => brand.isPremium);
}

export function getLocalBrands(country: string): typeof brands {
  return brands.filter(brand => brand.country === country);
}

export function getVerifiedBrands(): typeof brands {
  return brands.filter(brand => brand.isVerified);
}

export const brandCategories = {
  electronics: ['apple', 'samsung', 'sony', 'huawei', 'xiaomi', 'tecno', 'infinix', 'dell', 'hp', 'lenovo', 'lg', 'canon'],
  fashion: ['nike', 'adidas', 'puma'],
  home_garden: ['lg', 'bosch', 'philips', 'unilever', 'nestle'],
  automotive: ['bosch', 'kim-fay'],
  beauty_health: ['unilever', 'colgate'],
  sports_outdoors: ['nike', 'adidas', 'puma'],
  toys_games: ['nintendo', 'lego'],
} as const;

export function getBrandsForCategory(categoryId: string): BrandId[] {
  return brandCategories[categoryId as keyof typeof brandCategories] || [];
}

export const brandQualityTiers = {
  premium: ['apple', 'samsung', 'nike', 'adidas', 'sony', 'dell', 'hp', 'lg', 'bosch', 'philips', 'canon', 'nintendo', 'lego'],
  midrange: ['huawei', 'xiaomi', 'lenovo', 'puma', 'unilever', 'colgate', 'nestle'],
  budget: ['tecno', 'infinix', 'brookside', 'kim-fay', 'bidco'],
} as const;

export function getBrandQualityTier(brandId: BrandId): 'premium' | 'midrange' | 'budget' {
  if (brandQualityTiers.premium.includes(brandId)) return 'premium';
  if (brandQualityTiers.midrange.includes(brandId)) return 'midrange';
  return 'budget';
}

export const brandWarrantyPeriods: Record<BrandId, number> = {
  apple: 12,
  samsung: 12,
  nike: 0,
  adidas: 0,
  sony: 12,
  huawei: 12,
  xiaomi: 12,
  tecno: 12,
  infinix: 12,
  safaricom: 12,
  brookside: 0,
  'kim-fay': 6,
  bidco: 0,
  dell: 12,
  hp: 12,
  lenovo: 12,
  lg: 12,
  bosch: 24,
  philips: 12,
  unilever: 0,
  puma: 0,
  canon: 12,
  nintendo: 12,
  lego: 0,
  colgate: 0,
  nestle: 0,
};

export function getBrandWarranty(brandId: BrandId): number {
  return brandWarrantyPeriods[brandId] || 0;
}
