export const navigation = {
  main: [
    { name: 'Shop', href: '/shop', icon: '🛍️' },
    { name: 'Deals', href: '/deals', icon: '🔥' },
    { name: 'Categories', href: '/categories', icon: '📂' },
    { name: 'Brands', href: '/brands', icon: '🏷️' },
    { name: 'Collections', href: '/collections', icon: '📦' },
    { name: 'New Arrivals', href: '/new-arrivals', icon: '🆕' },
  ],
  categories: [
    { name: 'Electronics', href: '/category/electronics', count: 1240 },
    { name: 'Fashion', href: '/category/fashion', count: 856 },
    { name: 'Home & Garden', href: '/category/home-garden', count: 720 },
    { name: 'Beauty & Health', href: '/category/beauty-health', count: 430 },
    { name: 'Sports & Outdoors', href: '/category/sports-outdoors', count: 310 },
    { name: 'Automotive', href: '/category/automotive', count: 280 },
    { name: 'Toys & Games', href: '/category/toys-games', count: 190 },
    { name: 'Books & Media', href: '/category/books-media', count: 165 },
  ],
  user: [
    { name: 'My Account', href: '/account', icon: '👤' },
    { name: 'Orders', href: '/account/orders', icon: '📦' },
    { name: 'Wishlist', href: '/account/wishlist', icon: '❤️' },
    { name: 'My Wardrobe', href: '/account/wardrobe', icon: '👕' },
    { name: 'Addresses', href: '/account/addresses', icon: '📍' },
    { name: 'Payment Methods', href: '/account/payments', icon: '💳' },
    { name: 'Settings', href: '/account/settings', icon: '⚙️' },
  ],
  help: [
    { name: 'Help Center', href: '/help', icon: '❓' },
    { name: 'Contact Us', href: '/help/contact', icon: '📞' },
    { name: 'Shipping Info', href: '/help/shipping', icon: '🚚' },
    { name: 'Returns & Refunds', href: '/help/returns', icon: '🔄' },
    { name: 'FAQ', href: '/help/faq', icon: '📝' },
    { name: 'Track Order', href: '/track-order', icon: '📍' },
  ],
  legal: [
    { name: 'Terms of Service', href: '/legal/terms', icon: '📜' },
    { name: 'Privacy Policy', href: '/legal/privacy', icon: '🔒' },
    { name: 'Cookie Policy', href: '/legal/cookies', icon: '🍪' },
    { name: 'Accessibility', href: '/legal/accessibility', icon: '♿' },
    { name: 'Sitemap', href: '/sitemap.xml', icon: '🗺️' },
  ],
  footer: [
    { name: 'About Us', href: '/about' },
    { name: 'Careers', href: '/careers' },
    { name: 'Press', href: '/press' },
    { name: 'Affiliates', href: '/affiliates' },
    { name: 'Sell on Xarastore', href: '/sell' },
    { name: 'Business', href: '/business' },
  ],
  social: [
    { name: 'Facebook', href: 'https://facebook.com/xarastore', icon: 'facebook' },
    { name: 'Twitter', href: 'https://twitter.com/xarastore', icon: 'twitter' },
    { name: 'Instagram', href: 'https://instagram.com/xarastore', icon: 'instagram' },
    { name: 'YouTube', href: 'https://youtube.com/xarastore', icon: 'youtube' },
    { name: 'LinkedIn', href: 'https://linkedin.com/company/xarastore', icon: 'linkedin' },
    { name: 'TikTok', href: 'https://tiktok.com/@xarastore', icon: 'tiktok' },
  ],
} as const;
